package com.example.demo.model;

public enum Token {
    IDENTIFICADOR,CADENA,NUMERO,DECIMAL,MAS,MENOS,MULTIPLICACION,DIVICION,PALABRA_CLAVE,INVALIDO,
    OPERADOR_ASIGNACION,PUNTOYCOMA, PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,COMA,PUTNO,DOS_PUNTOS,COLON,IGUAL, MENOR_IGUAL, MAYOR_IGUAL, DIFERENTE, MAYOR_QUE, MENOR_QUE, ASIGNACION,
    LEFT_BRACE, RIGHT_BRACE,
        ARITMETICOS, COMPARACION, OTROS, CONSTANTES, LOGICOS
}
